apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplemicroservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simplemicroservice
  template:
    metadata:
      labels:
        app: simplemicroservice
    spec:
      containers:
      
      - name: simplemicroservice
        image: simplemicroservice
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: HOST
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: PORT      
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_PASSWORD   
        - name: JWTSECRET
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: JWTSECRET       
        ports:
        - containerPort: 3000
