apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jobapi
  template:
    metadata:
      labels:
        app: jobapi
    spec:
      containers:
      - name: jobapi
        image: jobapi
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: HOST
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: PORT      
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_PASSWORD   
        - name: JWTSECRET
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: JWTSECRET       
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: jobapi
spec:
  type: ClusterIP
  selector:
    app: jobapi
  ports:
  - port: 3000
    targetPort: 3000

