apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-pv1
  
spec:

  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: E:/Madareke Mehrbod/important/kubernetes pvs/pv1  # Update this path

    
